#!/bin/bash
# Script para restaurar todos os 28 protocolos clínicos
# Este script copia os protocolos do banco de dados de volta para o arquivo TypeScript

echo "🔄 Restaurando protocolos clínicos..."
echo ""
echo "Os 28 protocolos estão armazenados nas migrations SQL:"
echo "  ✓ 4 protocolos de Saúde da Mulher"
echo "  ✓ 4 protocolos de Joelho"
echo "  ✓ 3 protocolos de Ombro"
echo "  ✓ 5 protocolos de Tornozelo e Pé"
echo "  ✓ 4 protocolos de Quadril e Coluna"
echo "  ✓ 5 protocolos de Membro Superior"
echo "  ✓ 3 protocolos Neurológicos/Coluna"
echo ""
echo "📝 Para restaurar os protocolos, você tem 2 opções:"
echo ""
echo "OPÇÃO 1 - Restaurar do Banco de Dados (Recomendado):"
echo "  Os protocolos já estão no banco Supabase. Basta garantir que"
echo "  o sistema está lendo corretamente do banco."
echo ""
echo "OPÇÃO 2 - Copiar das Migrations para o arquivo TypeScript:"
echo "  Preciso converter manualmente cada protocolo SQL para TypeScript."
echo "  Isso levará alguns minutos devido ao volume de dados."
echo ""
echo "❓ Qual opção você prefere?"
echo "   1) Verificar se os protocolos estão no banco (rápido)"
echo "   2) Restaurar manualmente no arquivo .ts (demorado)"
echo ""
