-- Add missing columns to Profiles
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS slot_interval INTEGER DEFAULT 30;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS allow_overbooking BOOLEAN DEFAULT FALSE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS online_booking_enabled BOOLEAN DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS min_advance_booking_days INTEGER DEFAULT 2;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS has_agenda BOOLEAN DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS notify_whatsapp BOOLEAN DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS notify_email BOOLEAN DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS notify_sms BOOLEAN DEFAULT FALSE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS council_type TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS council_number TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS specialty TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS color TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS address_zip TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS address_street TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS address_number TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS address_complement TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS address_neighborhood TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS address_city TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS address_state TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS role_id UUID;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS date_of_birth DATE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS cpf TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS gender TEXT;

-- Add missing columns to Appointments
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS is_extra BOOLEAN DEFAULT FALSE;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS invoice_id UUID;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS google_event_id TEXT;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'appointment';
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS original_price NUMERIC;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS discount NUMERIC;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS addition NUMERIC;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS payment_method_id UUID;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS invoice_issued BOOLEAN DEFAULT FALSE;
